version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /src/Doturn
      - /test/Doturn.Test
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: monthly
    groups:
      docker-devcontainer:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    groups:
      docker-compose:
        patterns:
          - "*"
