version: '3'
services:
  doturn:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command: dotnet run
    working_dir: /usr/local/src/src/Doturn
    volumes:
      - .:/usr/local/src
  coturn:
    image: ghcr.io/coturn/coturn:latest
    tty: true