FROM mcr.microsoft.com/devcontainers/dotnet:8.0-noble
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    build-essential \
    coturn \
    tcpdump \
    wget \
    vnstat \
    vnstati