name: draft

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  add-draft-label:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        timeout-minutes: 5
        id: add-draft-label-to-new-issue
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['draft']
            });
