name: STUN E2E Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy config file
        run: cp ./src/Doturn/appsettings.sample.json ./src/Doturn/appsettings.json
      - name: Start Server
        run: docker-compose -f docker-compose.test.yml up -d
      - name: Wait for server
        run: sleep 10s
      - name: Test
        run: docker-compose -f docker-compose.test.yml exec -T coturn turnutils_stunclient doturn
        timeout-minutes: 1
      - name: Terminate Server
        run: docker-compose -f docker-compose.test.yml down
