name: Unit Test

on:
  push:
    paths:
      - '**.cs'
      - '**.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Doturn/
    - name: Copy settings file
      run: cp appsettings.sample.json appsettings.json
      working-directory: src/Doturn
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Doturn/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: test/Doturn.Test/
